package view;

public enum MenuType {
    NONE,
    PAUSE,
    SETTING,
    PROFILE,
    NEWS,
    TRAVEL_LOG,
    PLANT_SELECTOR,
    SHOP,
    I_ZOMBIE_MODE,
    I_ZOMBIE_QUEUE,
    I_ZOMBIE_INVITE,
    QUICK_MESSAGES,
    MATCH_RESTART,
    MATCH_RESTART_WAIT,
    MATCH_RESULT
}
